[package]
name = "spider_utils"
version = "2.21.6"
authors = [
    "j-mendez <jeff@spider.cloud>"
]
description = "Utilities to use for Spider Web Crawler."
repository = "https://github.com/spider-rs/spider"
readme = "README.md"
keywords = ["crawler", "spider"]
categories = ["web-programming", "command-line-utilities"]
license = "MIT"
documentation = "https://docs.rs/spider"
edition = "2018"

[dependencies]
indexmap = { version = "1", optional = true }
sxd-document = "0.3"
sxd-xpath = "0.4"
serde = { version = "1", optional = true, features = ["derive"] }

[dependencies.spider]
version = "2"
path = "../spider"

[dependencies.spider_transformations]
version = "2"
path = "../spider_transformations"
optional = true

[features]
default = []
indexset = ["indexmap"]
serde = ["dep:serde", "indexmap/serde", "spider/serde"]
transformations = ["dep:spider_transformations"]